from data_wrappers.data.item_data import item_data
from typing import Optional, TYPE_CHECKING
if TYPE_CHECKING:
    from resource import _Resource
    from npc_item import _NpcItem
    from craft import Craft
    from drop import Drop, Drops
    from effect import _Effect


class _Item:
    items = {}
    item_effect = {}
    
    def __init__(self, data):
        self.data = data
        self.resource: _Resource = None
        self.craft: Craft = None
        self.is_material = False
        self.processed_item: _Item = None
        self.npc_item: _NpcItem = None
        self.drops: Drops = None
        self.effects: dict[_Effect: int] = {}
        
        self.set_data(data)
        _Item.items[self.code] = self

    def __repr__(self):
        return self.name
        
    def set_data(self, data):
        self._set_data(data)
    
    ##### AUTO-GENERATED SECTION #####
    # annotate with # custom if you don't want code to be overwritten
    
    def _set_data(self, data):
        # _set_data start
        self.name = data.get('name', None)
        self.code = data.get('code', None)
        self.level = data.get('level', None)
        self.type = data.get('type', None)
        self.subtype = data.get('subtype', None)
        self.description = data.get('description', None)
        self.effects = {}   # custom
        self.craft = data.get('craft', None)
        self.tradeable = data.get('tradeable', None)
        # _set_data end
        

class Item(_Item):
    @staticmethod
    def get(key) -> _Item:
        return _Item.items.get(key)
    
    @staticmethod
    def all() -> list[_Item]:
        return list(_Item.items.values())

    @staticmethod
    def get_effect(effect) -> list[_Item]:
        return _Item.item_effect.get(effect, [])
        
    # auto-attrs start
    cooked_gudgeon = _Item(item_data.get('cooked_gudgeon', {}))
    copper_dagger = _Item(item_data.get('copper_dagger', {}))
    copper_ore = _Item(item_data.get('copper_ore', {}))
    raw_chicken = _Item(item_data.get('raw_chicken', {}))
    copper_boots = _Item(item_data.get('copper_boots', {}))
    egg = _Item(item_data.get('egg', {}))
    copper_helmet = _Item(item_data.get('copper_helmet', {}))
    ash_wood = _Item(item_data.get('ash_wood', {}))
    cooked_chicken = _Item(item_data.get('cooked_chicken', {}))
    feather = _Item(item_data.get('feather', {}))
    gudgeon = _Item(item_data.get('gudgeon', {}))
    tasks_coin = _Item(item_data.get('tasks_coin', {}))
    copper = _Item(item_data.get('copper', {}))
    wooden_shield = _Item(item_data.get('wooden_shield', {}))
    wooden_staff = _Item(item_data.get('wooden_staff', {}))
    copper_ring = _Item(item_data.get('copper_ring', {}))
    ash_plank = _Item(item_data.get('ash_plank', {}))
    wooden_stick = _Item(item_data.get('wooden_stick', {}))
    apple = _Item(item_data.get('apple', {}))
    algae = _Item(item_data.get('algae', {}))
    sunflower = _Item(item_data.get('sunflower', {}))
    bag_of_gold = _Item(item_data.get('bag_of_gold', {}))
    small_bag_of_gold = _Item(item_data.get('small_bag_of_gold', {}))
    golden_egg = _Item(item_data.get('golden_egg', {}))
    recall_potion = _Item(item_data.get('recall_potion', {}))
    south_bank_potion = _Item(item_data.get('south_bank_potion', {}))
    yellow_slimeball = _Item(item_data.get('yellow_slimeball', {}))
    green_slimeball = _Item(item_data.get('green_slimeball', {}))
    copper_legs_armor = _Item(item_data.get('copper_legs_armor', {}))
    feather_coat = _Item(item_data.get('feather_coat', {}))
    fire_staff = _Item(item_data.get('fire_staff', {}))
    raw_beef = _Item(item_data.get('raw_beef', {}))
    cooked_beef = _Item(item_data.get('cooked_beef', {}))
    copper_armor = _Item(item_data.get('copper_armor', {}))
    milk_bucket = _Item(item_data.get('milk_bucket', {}))
    fried_eggs = _Item(item_data.get('fried_eggs', {}))
    sticky_dagger = _Item(item_data.get('sticky_dagger', {}))
    sticky_sword = _Item(item_data.get('sticky_sword', {}))
    life_amulet = _Item(item_data.get('life_amulet', {}))
    water_bow = _Item(item_data.get('water_bow', {}))
    small_health_potion = _Item(item_data.get('small_health_potion', {}))
    satchel = _Item(item_data.get('satchel', {}))
    blue_slimeball = _Item(item_data.get('blue_slimeball', {}))
    red_slimeball = _Item(item_data.get('red_slimeball', {}))
    cowhide = _Item(item_data.get('cowhide', {}))
    fire_and_earth_amulet = _Item(item_data.get('fire_and_earth_amulet', {}))
    iron_boots = _Item(item_data.get('iron_boots', {}))
    iron_sword = _Item(item_data.get('iron_sword', {}))
    leather_boots = _Item(item_data.get('leather_boots', {}))
    mushroom = _Item(item_data.get('mushroom', {}))
    cooked_shrimp = _Item(item_data.get('cooked_shrimp', {}))
    leather_armor = _Item(item_data.get('leather_armor', {}))
    adventurer_helmet = _Item(item_data.get('adventurer_helmet', {}))
    air_and_water_amulet = _Item(item_data.get('air_and_water_amulet', {}))
    greater_wooden_staff = _Item(item_data.get('greater_wooden_staff', {}))
    iron_armor = _Item(item_data.get('iron_armor', {}))
    iron_legs_armor = _Item(item_data.get('iron_legs_armor', {}))
    adventurer_vest = _Item(item_data.get('adventurer_vest', {}))
    iron_helm = _Item(item_data.get('iron_helm', {}))
    iron_ore = _Item(item_data.get('iron_ore', {}))
    leather_hat = _Item(item_data.get('leather_hat', {}))
    slime_shield = _Item(item_data.get('slime_shield', {}))
    iron = _Item(item_data.get('iron', {}))
    jasper_crystal = _Item(item_data.get('jasper_crystal', {}))
    cheese = _Item(item_data.get('cheese', {}))
    spruce_wood = _Item(item_data.get('spruce_wood', {}))
    iron_ring = _Item(item_data.get('iron_ring', {}))
    iron_dagger = _Item(item_data.get('iron_dagger', {}))
    spruce_plank = _Item(item_data.get('spruce_plank', {}))
    shrimp = _Item(item_data.get('shrimp', {}))
    magical_cure = _Item(item_data.get('magical_cure', {}))
    fire_bow = _Item(item_data.get('fire_bow', {}))
    iron_pickaxe = _Item(item_data.get('iron_pickaxe', {}))
    iron_axe = _Item(item_data.get('iron_axe', {}))
    spruce_fishing_rod = _Item(item_data.get('spruce_fishing_rod', {}))
    backpack = _Item(item_data.get('backpack', {}))
    earth_boost_potion = _Item(item_data.get('earth_boost_potion', {}))
    air_boost_potion = _Item(item_data.get('air_boost_potion', {}))
    fire_boost_potion = _Item(item_data.get('fire_boost_potion', {}))
    water_boost_potion = _Item(item_data.get('water_boost_potion', {}))
    leather_gloves = _Item(item_data.get('leather_gloves', {}))
    astralyte_crystal = _Item(item_data.get('astralyte_crystal', {}))
    enchanted_fabric = _Item(item_data.get('enchanted_fabric', {}))
    forest_ring = _Item(item_data.get('forest_ring', {}))
    leather_legs_armor = _Item(item_data.get('leather_legs_armor', {}))
    golden_shrimp = _Item(item_data.get('golden_shrimp', {}))
    flying_wing = _Item(item_data.get('flying_wing', {}))
    serpent_skin = _Item(item_data.get('serpent_skin', {}))
    air_ring = _Item(item_data.get('air_ring', {}))
    multislimes_sword = _Item(item_data.get('multislimes_sword', {}))
    mushmush_wizard_hat = _Item(item_data.get('mushmush_wizard_hat', {}))
    raw_wolf_meat = _Item(item_data.get('raw_wolf_meat', {}))
    earth_ring = _Item(item_data.get('earth_ring', {}))
    lucky_wizard_hat = _Item(item_data.get('lucky_wizard_hat', {}))
    mushmush_jacket = _Item(item_data.get('mushmush_jacket', {}))
    adventurer_boots = _Item(item_data.get('adventurer_boots', {}))
    adventurer_pants = _Item(item_data.get('adventurer_pants', {}))
    cooked_wolf_meat = _Item(item_data.get('cooked_wolf_meat', {}))
    mushstaff = _Item(item_data.get('mushstaff', {}))
    fire_ring = _Item(item_data.get('fire_ring', {}))
    mushmush_bow = _Item(item_data.get('mushmush_bow', {}))
    wolf_bone = _Item(item_data.get('wolf_bone', {}))
    life_ring = _Item(item_data.get('life_ring', {}))
    mushroom_soup = _Item(item_data.get('mushroom_soup', {}))
    water_ring = _Item(item_data.get('water_ring', {}))
    wolf_hair = _Item(item_data.get('wolf_hair', {}))
    highwayman_dagger = _Item(item_data.get('highwayman_dagger', {}))
    green_cloth = _Item(item_data.get('green_cloth', {}))
    wisdom_amulet = _Item(item_data.get('wisdom_amulet', {}))
    wolf_ears = _Item(item_data.get('wolf_ears', {}))
    skeleton_bone = _Item(item_data.get('skeleton_bone', {}))
    skeleton_skull = _Item(item_data.get('skeleton_skull', {}))
    birch_wood = _Item(item_data.get('birch_wood', {}))
    magic_wizard_hat = _Item(item_data.get('magic_wizard_hat', {}))
    cooked_trout = _Item(item_data.get('cooked_trout', {}))
    ogre_skin = _Item(item_data.get('ogre_skin', {}))
    ring_of_chance = _Item(item_data.get('ring_of_chance', {}))
    battlestaff = _Item(item_data.get('battlestaff', {}))
    forest_whip = _Item(item_data.get('forest_whip', {}))
    ogre_eye = _Item(item_data.get('ogre_eye', {}))
    coal = _Item(item_data.get('coal', {}))
    steel_helm = _Item(item_data.get('steel_helm', {}))
    steel_boots = _Item(item_data.get('steel_boots', {}))
    hardwood_plank = _Item(item_data.get('hardwood_plank', {}))
    trout = _Item(item_data.get('trout', {}))
    steel_armor = _Item(item_data.get('steel_armor', {}))
    steel_battleaxe = _Item(item_data.get('steel_battleaxe', {}))
    steel_legs_armor = _Item(item_data.get('steel_legs_armor', {}))
    skeleton_pants = _Item(item_data.get('skeleton_pants', {}))
    skull_staff = _Item(item_data.get('skull_staff', {}))
    skeleton_armor = _Item(item_data.get('skeleton_armor', {}))
    skeleton_helmet = _Item(item_data.get('skeleton_helmet', {}))
    steel = _Item(item_data.get('steel', {}))
    dreadful_ring = _Item(item_data.get('dreadful_ring', {}))
    sapphire = _Item(item_data.get('sapphire', {}))
    emerald = _Item(item_data.get('emerald', {}))
    steel_shield = _Item(item_data.get('steel_shield', {}))
    steel_ring = _Item(item_data.get('steel_ring', {}))
    ruby = _Item(item_data.get('ruby', {}))
    pig_skin = _Item(item_data.get('pig_skin', {}))
    tromatising_mask = _Item(item_data.get('tromatising_mask', {}))
    skull_ring = _Item(item_data.get('skull_ring', {}))
    topaz = _Item(item_data.get('topaz', {}))
    dreadful_amulet = _Item(item_data.get('dreadful_amulet', {}))
    skull_amulet = _Item(item_data.get('skull_amulet', {}))
    minor_health_potion = _Item(item_data.get('minor_health_potion', {}))
    serpent_skin_boots = _Item(item_data.get('serpent_skin_boots', {}))
    apple_pie = _Item(item_data.get('apple_pie', {}))
    emerald_stone = _Item(item_data.get('emerald_stone', {}))
    topaz_stone = _Item(item_data.get('topaz_stone', {}))
    ruby_stone = _Item(item_data.get('ruby_stone', {}))
    sapphire_stone = _Item(item_data.get('sapphire_stone', {}))
    nettle_leaf = _Item(item_data.get('nettle_leaf', {}))
    small_antidote = _Item(item_data.get('small_antidote', {}))
    lifesteal_rune = _Item(item_data.get('lifesteal_rune', {}))
    burn_rune = _Item(item_data.get('burn_rune', {}))
    old_boots = _Item(item_data.get('old_boots', {}))
    spider_leg = _Item(item_data.get('spider_leg', {}))
    hunting_bow = _Item(item_data.get('hunting_bow', {}))
    healing_rune = _Item(item_data.get('healing_rune', {}))
    silver_chalice = _Item(item_data.get('silver_chalice', {}))
    vampire_blood = _Item(item_data.get('vampire_blood', {}))
    vampire_tooth = _Item(item_data.get('vampire_tooth', {}))
    dreadful_staff = _Item(item_data.get('dreadful_staff', {}))
    bandit_armor = _Item(item_data.get('bandit_armor', {}))
    skull_wand = _Item(item_data.get('skull_wand', {}))
    lizard_skin_armor = _Item(item_data.get('lizard_skin_armor', {}))
    serpent_skin_legs_armor = _Item(item_data.get('serpent_skin_legs_armor', {}))
    lizard_skin_legs_armor = _Item(item_data.get('lizard_skin_legs_armor', {}))
    piggy_pants = _Item(item_data.get('piggy_pants', {}))
    topaz_amulet = _Item(item_data.get('topaz_amulet', {}))
    emerald_amulet = _Item(item_data.get('emerald_amulet', {}))
    lizard_skin = _Item(item_data.get('lizard_skin', {}))
    sapphire_amulet = _Item(item_data.get('sapphire_amulet', {}))
    ruby_amulet = _Item(item_data.get('ruby_amulet', {}))
    serpent_skin_armor = _Item(item_data.get('serpent_skin_armor', {}))
    cyclops_eye = _Item(item_data.get('cyclops_eye', {}))
    piggy_helmet = _Item(item_data.get('piggy_helmet', {}))
    piggy_armor = _Item(item_data.get('piggy_armor', {}))
    stormforged_armor = _Item(item_data.get('stormforged_armor', {}))
    stormforged_pants = _Item(item_data.get('stormforged_pants', {}))
    wooden_club = _Item(item_data.get('wooden_club', {}))
    vampire_bow = _Item(item_data.get('vampire_bow', {}))
    lizard_eye = _Item(item_data.get('lizard_eye', {}))
    dreadful_book = _Item(item_data.get('dreadful_book', {}))
    red_cloth = _Item(item_data.get('red_cloth', {}))
    demoniac_dust = _Item(item_data.get('demoniac_dust', {}))
    greater_dreadful_staff = _Item(item_data.get('greater_dreadful_staff', {}))
    owlbear_hair = _Item(item_data.get('owlbear_hair', {}))
    death_knight_sword = _Item(item_data.get('death_knight_sword', {}))
    cooked_bass = _Item(item_data.get('cooked_bass', {}))
    gold_platebody = _Item(item_data.get('gold_platebody', {}))
    gold_shield = _Item(item_data.get('gold_shield', {}))
    ruby_ring = _Item(item_data.get('ruby_ring', {}))
    life_crystal = _Item(item_data.get('life_crystal', {}))
    gold = _Item(item_data.get('gold', {}))
    bass = _Item(item_data.get('bass', {}))
    gold_platelegs = _Item(item_data.get('gold_platelegs', {}))
    gold_sword = _Item(item_data.get('gold_sword', {}))
    lich_crown = _Item(item_data.get('lich_crown', {}))
    dead_wood = _Item(item_data.get('dead_wood', {}))
    gold_ore = _Item(item_data.get('gold_ore', {}))
    gold_mask = _Item(item_data.get('gold_mask', {}))
    dead_wood_plank = _Item(item_data.get('dead_wood_plank', {}))
    topaz_ring = _Item(item_data.get('topaz_ring', {}))
    gold_ring = _Item(item_data.get('gold_ring', {}))
    gold_fishing_rod = _Item(item_data.get('gold_fishing_rod', {}))
    demon_horn = _Item(item_data.get('demon_horn', {}))
    gold_axe = _Item(item_data.get('gold_axe', {}))
    gold_helm = _Item(item_data.get('gold_helm', {}))
    sapphire_ring = _Item(item_data.get('sapphire_ring', {}))
    emerald_ring = _Item(item_data.get('emerald_ring', {}))
    gold_pickaxe = _Item(item_data.get('gold_pickaxe', {}))
    lizard_boots = _Item(item_data.get('lizard_boots', {}))
    gold_boots = _Item(item_data.get('gold_boots', {}))
    greater_dreadful_amulet = _Item(item_data.get('greater_dreadful_amulet', {}))
    piece_of_obsidian = _Item(item_data.get('piece_of_obsidian', {}))
    obsidian = _Item(item_data.get('obsidian', {}))
    sap = _Item(item_data.get('sap', {}))
    obsidian_legs_armor = _Item(item_data.get('obsidian_legs_armor', {}))
    obsidian_helmet = _Item(item_data.get('obsidian_helmet', {}))
    obsidian_armor = _Item(item_data.get('obsidian_armor', {}))
    health_potion = _Item(item_data.get('health_potion', {}))
    golden_gloves = _Item(item_data.get('golden_gloves', {}))
    lost_amulet = _Item(item_data.get('lost_amulet', {}))
    royal_skeleton_pants = _Item(item_data.get('royal_skeleton_pants', {}))
    royal_skeleton_armor = _Item(item_data.get('royal_skeleton_armor', {}))
    royal_skeleton_helmet = _Item(item_data.get('royal_skeleton_helmet', {}))
    elderwood_staff = _Item(item_data.get('elderwood_staff', {}))
    obsidian_battleaxe = _Item(item_data.get('obsidian_battleaxe', {}))
    antidote = _Item(item_data.get('antidote', {}))
    prospecting_amulet = _Item(item_data.get('prospecting_amulet', {}))
    enchanted_bow = _Item(item_data.get('enchanted_bow', {}))
    royal_skeleton_ring = _Item(item_data.get('royal_skeleton_ring', {}))
    owlbear_claw = _Item(item_data.get('owlbear_claw', {}))
    flying_boots = _Item(item_data.get('flying_boots', {}))
    conjurer_skirt = _Item(item_data.get('conjurer_skirt', {}))
    conjurer_cloak = _Item(item_data.get('conjurer_cloak', {}))
    golden_chalice = _Item(item_data.get('golden_chalice', {}))
    cursed_book = _Item(item_data.get('cursed_book', {}))
    magic_stone = _Item(item_data.get('magic_stone', {}))
    malefic_cloth = _Item(item_data.get('malefic_cloth', {}))
    strange_ore = _Item(item_data.get('strange_ore', {}))
    diamond = _Item(item_data.get('diamond', {}))
    magic_wood = _Item(item_data.get('magic_wood', {}))
    strangold = _Item(item_data.get('strangold', {}))
    magical_plank = _Item(item_data.get('magical_plank', {}))
    cursed_hat = _Item(item_data.get('cursed_hat', {}))
    strangold_helmet = _Item(item_data.get('strangold_helmet', {}))
    strangold_legs_armor = _Item(item_data.get('strangold_legs_armor', {}))
    strangold_armor = _Item(item_data.get('strangold_armor', {}))
    malefic_armor = _Item(item_data.get('malefic_armor', {}))
    magic_bow = _Item(item_data.get('magic_bow', {}))
    cursed_sceptre = _Item(item_data.get('cursed_sceptre', {}))
    diamond_amulet = _Item(item_data.get('diamond_amulet', {}))
    magic_stone_amulet = _Item(item_data.get('magic_stone_amulet', {}))
    magic_sap = _Item(item_data.get('magic_sap', {}))
    strangold_sword = _Item(item_data.get('strangold_sword', {}))
    ancient_jean = _Item(item_data.get('ancient_jean', {}))
    greater_health_potion = _Item(item_data.get('greater_health_potion', {}))
    diamond_stone = _Item(item_data.get('diamond_stone', {}))
    goblin_tooth = _Item(item_data.get('goblin_tooth', {}))
    masterful_necklace = _Item(item_data.get('masterful_necklace', {}))
    ancestral_talisman = _Item(item_data.get('ancestral_talisman', {}))
    dreadful_armor = _Item(item_data.get('dreadful_armor', {}))
    dreadful_shield = _Item(item_data.get('dreadful_shield', {}))
    dreadful_battleaxe = _Item(item_data.get('dreadful_battleaxe', {}))
    goblin_eye = _Item(item_data.get('goblin_eye', {}))
    malefic_crystal = _Item(item_data.get('malefic_crystal', {}))
    malefic_ring = _Item(item_data.get('malefic_ring', {}))
    diamond_sword = _Item(item_data.get('diamond_sword', {}))
    jester_hat = _Item(item_data.get('jester_hat', {}))
    enchanter_pants = _Item(item_data.get('enchanter_pants', {}))
    enchanter_boots = _Item(item_data.get('enchanter_boots', {}))
    cursed_wood = _Item(item_data.get('cursed_wood', {}))
    cursed_plank = _Item(item_data.get('cursed_plank', {}))
    bat_wing = _Item(item_data.get('bat_wing', {}))
    orc_skin = _Item(item_data.get('orc_skin', {}))
    fish_soup = _Item(item_data.get('fish_soup', {}))
    sanguine_edge_of_rosen = _Item(item_data.get('sanguine_edge_of_rosen', {}))
    fire_shield = _Item(item_data.get('fire_shield', {}))
    water_shield = _Item(item_data.get('water_shield', {}))
    air_shield = _Item(item_data.get('air_shield', {}))
    earth_shield = _Item(item_data.get('earth_shield', {}))
    rosenblood_elixir = _Item(item_data.get('rosenblood_elixir', {}))
    batwing_helmet = _Item(item_data.get('batwing_helmet', {}))
    salmon = _Item(item_data.get('salmon', {}))
    cooked_salmon = _Item(item_data.get('cooked_salmon', {}))
    health_boost_potion = _Item(item_data.get('health_boost_potion', {}))
    wolfrider_hair = _Item(item_data.get('wolfrider_hair', {}))
    hork_helmet = _Item(item_data.get('hork_helmet', {}))
    glowstem_leaf = _Item(item_data.get('glowstem_leaf', {}))
    mithril_ore = _Item(item_data.get('mithril_ore', {}))
    mithril = _Item(item_data.get('mithril', {}))
    maple_plank = _Item(item_data.get('maple_plank', {}))
    maple_wood = _Item(item_data.get('maple_wood', {}))
    enchanted_health_potion = _Item(item_data.get('enchanted_health_potion', {}))
    enchanted_boost_potion = _Item(item_data.get('enchanted_boost_potion', {}))
    hellhound_bone = _Item(item_data.get('hellhound_bone', {}))
    broken_sword = _Item(item_data.get('broken_sword', {}))
    hellhound_hair = _Item(item_data.get('hellhound_hair', {}))
    raw_hellhound_meat = _Item(item_data.get('raw_hellhound_meat', {}))
    cooked_hellhound_meat = _Item(item_data.get('cooked_hellhound_meat', {}))
    greater_emerald_amulet = _Item(item_data.get('greater_emerald_amulet', {}))
    greater_sapphire_amulet = _Item(item_data.get('greater_sapphire_amulet', {}))
    greater_topaz_amulet = _Item(item_data.get('greater_topaz_amulet', {}))
    greater_ruby_amulet = _Item(item_data.get('greater_ruby_amulet', {}))
    mithril_sword = _Item(item_data.get('mithril_sword', {}))
    mithril_platebody = _Item(item_data.get('mithril_platebody', {}))
    mithril_helm = _Item(item_data.get('mithril_helm', {}))
    mithril_platelegs = _Item(item_data.get('mithril_platelegs', {}))
    bow_from_hell = _Item(item_data.get('bow_from_hell', {}))
    hell_staff = _Item(item_data.get('hell_staff', {}))
    lightning_sword = _Item(item_data.get('lightning_sword', {}))
    ruby_book = _Item(item_data.get('ruby_book', {}))
    emerald_book = _Item(item_data.get('emerald_book', {}))
    sapphire_book = _Item(item_data.get('sapphire_book', {}))
    topaz_book = _Item(item_data.get('topaz_book', {}))
    demoniac_dagger = _Item(item_data.get('demoniac_dagger', {}))
    bloodblade = _Item(item_data.get('bloodblade', {}))
    wrathsword = _Item(item_data.get('wrathsword', {}))
    sacred_ring = _Item(item_data.get('sacred_ring', {}))
    divinity_ring = _Item(item_data.get('divinity_ring', {}))
    eternity_ring = _Item(item_data.get('eternity_ring', {}))
    cultist_cloak = _Item(item_data.get('cultist_cloak', {}))
    wratharmor = _Item(item_data.get('wratharmor', {}))
    hell_armor = _Item(item_data.get('hell_armor', {}))
    white_knight_armor = _Item(item_data.get('white_knight_armor', {}))
    cultist_pants = _Item(item_data.get('cultist_pants', {}))
    wrathpants = _Item(item_data.get('wrathpants', {}))
    hell_legs_armor = _Item(item_data.get('hell_legs_armor', {}))
    white_knight_pants = _Item(item_data.get('white_knight_pants', {}))
    cultist_hat = _Item(item_data.get('cultist_hat', {}))
    wrathelmet = _Item(item_data.get('wrathelmet', {}))
    white_knight_helmet = _Item(item_data.get('white_knight_helmet', {}))
    cultist_boots = _Item(item_data.get('cultist_boots', {}))
    mithril_boots = _Item(item_data.get('mithril_boots', {}))
    mithril_shield = _Item(item_data.get('mithril_shield', {}))
    white_knight_shield = _Item(item_data.get('white_knight_shield', {}))
    blade_of_hell = _Item(item_data.get('blade_of_hell', {}))
    book_from_hell = _Item(item_data.get('book_from_hell', {}))
    efreet_cloth = _Item(item_data.get('efreet_cloth', {}))
    maple_sap = _Item(item_data.get('maple_sap', {}))
    maple_syrup = _Item(item_data.get('maple_syrup', {}))
    earth_res_potion = _Item(item_data.get('earth_res_potion', {}))
    fire_res_potion = _Item(item_data.get('fire_res_potion', {}))
    water_res_potion = _Item(item_data.get('water_res_potion', {}))
    air_res_potion = _Item(item_data.get('air_res_potion', {}))
    celest_ring = _Item(item_data.get('celest_ring', {}))
    frozen_pickaxe = _Item(item_data.get('frozen_pickaxe', {}))
    frozen_gloves = _Item(item_data.get('frozen_gloves', {}))
    frozen_fishing_rod = _Item(item_data.get('frozen_fishing_rod', {}))
    frozen_axe = _Item(item_data.get('frozen_axe', {}))
    # auto-attrs end
  